# Generated by Django 6.0.1 on 2026-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genre_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Crime', 'Crime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Punjabi', 'Punjabi'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi')], max_length=20),
        ),
    ]
